### ISSUE TITLE
Any way to get these in an ISO compliant string?

### ISSUE THREAD

**Issue by lauraGgit** [18F/us-federal-holidays#1]
This would be helpful when using Moment.js.

http://momentjs.com/docs/#/parsing/string/

**Comment by lauraGgit** [comment]
Or at least format the `dateSring` to be consistently MM-DD-YYYY

**Comment by mgwalker** [comment]
The `allForYear(year)` method returns an array of holidays for that calendar year.  Each array is an object of the form:

``` javascript
{
    name: String,
    date: Date,
    dateString: String
}
```

The `date` property is a Javascript Date object, and you can call the [`Date.prototype.toISOString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) method on it.  E.g.:

``` javascript
var holidays = fedHolidays.allForYear(2016);
var iso = holidays[0].date.toISOString();
```

**Comment by mgwalker** [comment]
Or even better:

```js
var isoHolidays = fedHolidays.allForYear(2016).map(holiday => holiday.date.toISOString());
```

Gives you a nice array of ISO-formatted holiday date strings  😄
