### ISSUE TITLE
React-Native/Android Support

### ISSUE THREAD

**Issue by ian-speers** [18F/us-federal-holidays#21]
Hi there!

I'm using this lib in a `react-nattive` project and I noticed that the `inRange` function was returning an empty list when running on android. After poking around a bit, I realized that the dates generated in `allFederalHolidaysForYear` are invalid. Apparently the `Date.parse` implementation in the Android JS runtime can't handle the current format. 

I opened a [PR](https://github.com/18F/us-federal-holidays/pull/20) to switch the date format to `ISO-8601`. I've run my project with the updates in the PR branch and everything is working correctly.

Let me know if you have any questions or if you'd like to discuss further. Otherwise—would you mind reviewing+merging the linked PR when you have a chance? Thanks!

**Comment by mgwalker** [comment]
Closed by #26, published in [version 2.0.0](https://www.npmjs.com/package/@18f/us-federal-holidays/v/2.0.0)
