### ISSUE TITLE
Black Friday Holiday

### ISSUE THREAD

**Issue by g4rry420** [18F/us-federal-holidays#37]
Hii, please add black friday for the US. Thank you

**Comment by mgwalker** [comment]
Hi there, thanks for commenting! There is no "black Friday" holiday in the United States. Please refer to the official list of holidays maintained by the [Office of Personnel Management (OMB)](https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/)

**Comment by g4rry420** [comment]
@mgwalker Thank you letting me know about this. Actually, the company where I worked has a specific requirement to put black friday into holiday list, Do you know how can I implement this ?

```
 // Black Friday Day
  // Fourth Friday of November
  holidays.push({
    name: `Thanksgiving Day`,
    date: getNthDayOf(5, 5, 11, year)
  });
```
I have used this approach using this repo codebase, but the holiday came as 3rd Dec, 2021. Can you please spot if I am making a mistake ?

**Comment by mgwalker** [comment]
I think `getNthDayOf(4, 5, 11, year)` should work. The function isn't very well documented, but it's:
- which repetition of the day
- which day of the week (0 = Sunday, 6 = Saturday)
- which month

So if Thanksgiving is the 4th Thursday of November (4, 4, 11), then Black Friday should be the 4th _Friday_, (4, 5, 11). I believe the sample code you posted would go to the 5th Friday of November, which is actually the 1st Friday of December.

**Comment by g4rry420** [comment]
Thank you, It worked.

**Comment by justin-edwards** [comment]
@g4rry420 your comment is over a year old so you may not need this anymore but I believe the above suggestion is not entirely correct. Black Friday is not the 4th Friday of November, it's the day after the 4th Thursday in November which means that sometimes it could be the 5th Friday in the month(i.e. when November 1st falls on a Friday, the 4th Friday is the week before Thanksgiving not the day after it). What I believe you actually need to do to accurately show black Friday is to get Thanksgiving day and then add one day to it.
