### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by mgwalker** [18F/us-federal-holidays#5]
Just as it says on the tin: this package could use some tests!

We need to be mindful about edge cases when testing this little library, like holidays that fall on weekends or where the *observed* holiday happens in one year while the actual holiday is in another year (e.g., December 31, 2010, was the observed holiday for New Year's Day 2011).

**Comment by createthis** [comment]
I'm working on this.

**Comment by createthis** [comment]
@mgwalker these have been implemented. See PR. They really accelerate development. I should have just made this change earlier.

**Comment by createthis** [comment]
@mgwalker this worked out fine. I just moved the tests that were dropped into my own project. That's almost certainly where they belonged anyway. Thanks.

**Comment by mgwalker** [comment]
Oh, perfect!  Would you be able to share a link to your project's source?  I'd be interested in seeing how you're using this library!
